apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: LAB-poi-map-app-dev
  annotations:
    argocd/app-name: LAB-poi-map-app-dev
    backstage.io/kubernetes-id: LAB-poi-map-app
    backstage.io/kubernetes-namespace: LAB
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/LAB-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/LAB/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/LAB/deployments/LAB-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/LAB-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://LAB-poi-map-app-LAB.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-LAB
  consumesApis:
    - gateway-api-LAB
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-LAB
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
